In [1]:
import numpy as np

In [2]:
matrices = np.load('sensitivity_coeff_matrix.npy')

In [3]:
matrices.shape

(1000, 144000, 8)

In [5]:
matrice0 = matrices[0]
matrice1 = matrices[1]

In [7]:
import pandas as pd

params_test = pd.read_csv('dataset_test.csv').iloc[:2, -8:]

In [13]:
params_sets = params_test.values

In [45]:
from generate_dataset_class import potassium_channel_dataset_genaerator
M_ha = 2
M_hb = 5
V_2ha = -40
V_2hb = -35
s_ha = 6
s_hb = -10
X_h = [M_ha, M_hb, V_2ha, V_2hb, s_ha, s_hb]

param_bounds_wo_h = {'g_max': [100.0, 140.0],
                'E_rev': [-100, -80],

                'M_ma': [0, 50],
                'M_mb': [0, 50],
                'V_2ma': [-60, 60],
                #'V_2ma': [10, 100],
                'V_2mb': [-60, 60],
                's_ma': [-50, -0.5],  # excluding small abs values to avoid operating error in exp
                's_mb': [0.5, 50]}

input = {'p': 4,
         'q': 0,
        'step_Vs': np.array([0.00, 10.00, 20.00, 30.00, 40.00, 50.00, 60.00, 70.00, 80.00]), # mV
        'prestep_Vs': np.array([-80, -50, -20]),
        'step_V': 80,
        'prestep_V': -100,  #mV
        'end_time': 120,
        'time_step': 0.01,
        'X_h': X_h,
        'param_bounds_wo_h': param_bounds_wo_h}

current_generator = potassium_channel_dataset_genaerator(input)
current_generator.generate_data_w_params(params_sets)
current_generator.current_traces_3d.shape

(2, 12, 12000)

In [46]:
current_generator.current_traces_3d[0]

array([[4.25438152e-01, 3.47401620e+01, 1.16513469e+02, ...,
        3.26313546e+02, 3.26313546e+02, 3.26313546e+02],
       [4.71191271e-01, 5.44961764e+01, 1.88910078e+02, ...,
        5.30546890e+02, 5.30546890e+02, 5.30546890e+02],
       [5.16944389e-01, 8.15907018e+01, 2.91657546e+02, ...,
        8.28715100e+02, 8.28715100e+02, 8.28715100e+02],
       ...,
       [4.51460184e+00, 5.40912725e+02, 2.05089696e+03, ...,
        7.23790337e+03, 7.23790337e+03, 7.23790337e+03],
       [4.33371919e+01, 8.82610605e+02, 2.52036377e+03, ...,
        7.23790337e+03, 7.23790337e+03, 7.23790337e+03],
       [2.48536945e+02, 1.52262682e+03, 3.22623586e+03, ...,
        7.23790337e+03, 7.23790337e+03, 7.23790337e+03]])

In [47]:
current_generator.current_traces_3d[0].reshape(-1, order='F')

array([4.25438152e-01, 4.71191271e-01, 5.16944389e-01, ...,
       7.23790337e+03, 7.23790337e+03, 7.23790337e+03])

In [48]:
y_col0 = current_generator.current_traces_3d[0].reshape(-1, order='F')
y_col1 = current_generator.current_traces_3d[1].reshape(-1, order='F')
y_col0.shape, y_col1.shape

((144000,), (144000,))

In [49]:
y_col0

array([4.25438152e-01, 4.71191271e-01, 5.16944389e-01, ...,
       7.23790337e+03, 7.23790337e+03, 7.23790337e+03])

In [50]:
np.tile(y_col0, (8, 1)).T.shape

(144000, 8)